services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    networks:
      - pnetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - .env:/app/.env
    env_file:
      - .env
    networks:
      - pnetwork
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine
    container_name: postgres-164
    ports:
      - "5432:5432"
    volumes:
      #- ./backend/scripts:/docker-entrypoint-initdb.d
      - phantomx-sql-data:/var/lib/postgresql/data
    networks:
      - pnetwork
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-setup:
    image: postgres:16.4-alpine
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/scripts:/scripts
    networks:
      - pnetwork
    env_file:
      - .env
    command: >
      sh -c "
        echo '🚀 Esperando a que PostgreSQL esté listo...'
        until pg_isready -h postgres -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
          echo '⏳ Esperando...'
          sleep 2
        done
        echo '✅ PostgreSQL listo, ejecutando configuración...'
        #Ejecutar como script bash, no como archivo SQL
        bash /scripts/00-init-db.sh
        echo '🎉 Configuración completada'
      "
    restart: "no"

volumes:
  phantomx-sql-data:
    external: true

networks:
  pnetwork:
    external: true
    #driver: bridge